### ISSUE TITLE
`structure_test` rule doesn't work

### ISSUE THREAD

**Issue by erain** [GoogleCloudPlatform/container-structure-test#21]
First of all, nice framework for docker image testing! 

I tried to use `structure_test ` rule with bazel with my image (produced by bazel `container_image` rule). However, I got the following error msg:

```
ERROR: <my-project>/BUILD:119:1: every rule of type structure_test implicitly depends upon the target '@structure_test//structure_tests:go_default_test', but this target could not be found because of: no such package '@structure_test//structure_tests': BUILD file not found on package path
```

When I looked into it, in [tests.bzl](https://github.com/GoogleCloudPlatform/container-structure-test/blob/master/tests.bzl#L66), the target `Label("//structure_tests:go_default_test")` is obviously missing. 

I guess the fix would be: 

- renamed `BUILD.oss` to `BUILD`
- have `Label("//structure_tests:go_default_test")` properly reference to it (maybe `Label("//:go_default_test")`)

**Comment by dlorenc** [comment]
Ah, sorry about this. We moved the bazel rule definition to a different repo (the same one as container_image): https://github.com/bazelbuild/rules_docker/blob/master/contrib/test.bzl

Could you try using that and let us know if it works for you? We should clean up the documentation and code that still remains in here.

**Comment by erain** [comment]
Unfortunately, the `@rules_docker//contrib:test.bzl` doesn't work as well. See the following line: 
https://github.com/bazelbuild/rules_docker/blob/8aeab63328a82fdb8e8eb12f677a4e5ce6b183b1/contrib/test.bzl#L93

**Comment by dlorenc** [comment]
We use it over here and it works: https://github.com/GoogleCloudPlatform/base-images-docker/blob/87dea08ae928698385154e9883a50765effd9b10/tests/util/BUILD#L77

What do you have in your WORKSPACE? You might need to update the build of rules_docker you use, the repositories() definition there should be pulling in @structure_test for you:
https://github.com/bazelbuild/rules_docker/blob/766df456abcad45534bea51fa4e628cac24badf6/container/container.bzl#L153

**Comment by nkubala** [comment]
@erain take a look at the example I set up over here: https://github.com/nkubala/structure-test-examples

I actually had an old version of rules_docker in my repo as well, but I just updated it and everything works fine now. If you model your WORKSPACE after the one I have here, you should be good. Sorry for the confusion!

**Comment by erain** [comment]
Now I know the problem! 

My previous error message was: 

ERROR: <my-project>: every rule of type _container_test implicitly depends upon the target '@structure_test//:go_default_test', but this target could not be found because of: error loading package '@structure_test//': Extension file not found. Unable to load package for '@io_bazel_rules_go//go:def.bzl': The repository could not be resolved

After adding the following dependencies in the WORKSPACE it started to work: 

```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    tag = "0.5.5",
)

load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_repositories",
)
go_repositories()
```

I had no idea that I need go as dependencies...

**Comment by nkubala** [comment]
Closing this for now, feel free to reach out if you run into more issues.
