### ISSUE TITLE
Pulling docker image fails with `Error response from daemon: manifest for gcr.io/gcp-runtimes/container-structure-test:latest not found`

### ISSUE THREAD

**Issue by brandon-fryslie** [GoogleCloudPlatform/container-structure-test#32]
Expected behavior:

I should be able to run `docker pull gcr.io/gcp-runtimes/container-structure-test` to get the container-structure-test docker image.

Actual behavior:

Running `docker pull gcr.io/gcp-runtimes/container-structure-test` fails with output `Error response from daemon: manifest for gcr.io/gcp-runtimes/container-structure-test:latest not found`

**Comment by kill0rz** [comment]
You could use a version, like `gcr.io/gcp-runtimes/container-structure-test:8432c055cea5342d2a5bef5ffc107072bd82931f`

**Comment by zemanlx** [comment]
There is no `latest` therefore you have to used tagged version, see its [GCR](https://console.cloud.google.com/gcr/images/gcp-runtimes/GLOBAL/container-structure-test?gcrImageListsize=50). They are matching repo [tags](https://github.com/GoogleCloudPlatform/container-structure-test/tags).

**Comment by nkubala** [comment]
I added some automation to tag the newest image releases with `latest`. Starting with the next release you should be able to pull the image with no tag.

**Comment by mvoitko** [comment]
@nkubala Hi. I am still facing the same issue. How could I resolve it?

**Comment by nkubala** [comment]
@mvoitko this should be resolved, and it seems to work for me:

```
➜  docker pull gcr.io/gcp-runtimes/container-structure-test
Using default tag: latest
latest: Pulling from gcp-runtimes/container-structure-test
24f0c933cbef: Already exists
69e2f037cdb3: Already exists
bbd26a3b2ccf: Pull complete
3251c8a3fa98: Pull complete
Digest: sha256:5e475f67ddf57a18c3558ec23cf7d3cfcaf75b4f3aedf1001b527dd20d84fa29
Status: Downloaded newer image for gcr.io/gcp-runtimes/container-structure-test:latest
gcr.io/gcp-runtimes/container-structure-test:latest
```
