### ISSUE TITLE
-save flag not working

### ISSUE THREAD

**Issue by atmoz** [GoogleCloudPlatform/container-structure-test#36]
The readme mentions the `-save` flag, but I get this error message when trying to use it:

    flag provided but not defined: -save

**Comment by nkubala** [comment]
Hey @atmoz, thanks for reporting. This was my fault, in my [example repo](https://github.com/nkubala/structure-test-examples) I linked to an old version of the code that had a lot of missing features. I've updated the links in that repo, using the latest released binary should fix this issue for you. Sorry for the confusion!

**Comment by atmoz** [comment]
I did not download from the example repo, I used the link from the readme in this repo.

Exact link: https://storage.googleapis.com/container-structure-test/latest/container-structure-test

I downloaded this again, but I see no difference.

This is the usage output:

```
Usage of container-structure-test:
  -driver string
    	driver to use when running tests (default "docker")
  -image string
    	path to test image
  -test.bench regexp
    	run only benchmarks matching regexp
  -test.benchmem
    	print memory allocations for benchmarks
  -test.benchtime d
    	run each benchmark for duration d (default 1s)
  -test.blockprofile file
    	write a goroutine blocking profile to file
  -test.blockprofilerate rate
    	set blocking profile rate (see runtime.SetBlockProfileRate) (default 1)
  -test.count n
    	run tests and benchmarks n times (default 1)
  -test.coverprofile file
    	write a coverage profile to file
  -test.cpu list
    	comma-separated list of cpu counts to run each test with
  -test.cpuprofile file
    	write a cpu profile to file
  -test.memprofile file
    	write a memory profile to file
  -test.memprofilerate rate
    	set memory profiling rate (see runtime.MemProfileRate)
  -test.mutexprofile string
    	write a mutex contention profile to the named file after execution
  -test.mutexprofilefraction int
    	if >= 0, calls runtime.SetMutexProfileFraction() (default 1)
  -test.outputdir dir
    	write profiles to dir
  -test.parallel n
    	run at most n tests in parallel (default 4)
  -test.run regexp
    	run only tests and examples matching regexp
  -test.short
    	run smaller test suite to save time
  -test.timeout d
    	fail test binary execution after duration d (0 means unlimited)
  -test.trace file
    	write an execution trace to file
  -test.v
    	verbose: print additional output
```

Notice there is no mentioning of any `-save` flag.

**Comment by nkubala** [comment]
Ah, sorry you're right. I grouped this with the issues from the old binary link because there were so many at once 😨 This is happening because we haven't done a release with the latest changes since before this issue was fixed. I'll be doing a release this afternoon, so once you upgrade to the latest version this should be fixed for you.

**Comment by oztigertim** [comment]
I just ran into this but found a workaround.
The -save needs to be before the yaml file on the command line.

This fails:
sudo ./container-structure-test -test.v -driver tar -image python python_file_test.yaml **-save**
with error:
2018/02/28 17:31:01 Error parsing config file: open -save: no such file or directory


This saves:
sudo ./container-structure-test -test.v -driver tar -image python **-save** python_file_test.yaml

**Comment by nkubala** [comment]
Yeah, the last CLI argument is one or more config files, which are positional so they have to be at the end. I'm working on a rewrite of the tool that changes the configs to be specified with a flag so they can be anywhere, which will make this more clear. Going to close this issue for now.
