### ISSUE TITLE
Updated Release Binary

### ISSUE THREAD

**Issue by goffinf** [GoogleCloudPlatform/container-structure-test#49]
I notice that there have been recent commits to resolve issues (now closed) for over-riding entrypoint and tidying up intermediate containers. However I downloaded the release binary from the link in this repo: https://storage.googleapis.com/container-structure-test/latest/container-structure-test but it looks like this is the same binary that I had previously been using when I raised those and running it the behaviours don't seem to have changed.

Is the release binary not yet updated to include those changes ?

Thx

Fraser

**Comment by nkubala** [comment]
Hey Fraser,

We had an issue with our release automation that prevented the latest binary from being released. I just built and published the latest binary, please try downloading it when you get a chance and verify that the fixes work for you.

**Comment by goffinf** [comment]
Hey Nick,

pulled updated release binary and all good. Containers are cleaned up and commands are not impacted for images with entrypoints.
