### ISSUE TITLE
setup for commandTests appears to be broken

### ISSUE THREAD

**Issue by cognitiaclaeves** [GoogleCloudPlatform/container-structure-test#55]
```
- name: curl localhost
  setup: [['/app-cfg/entrypoint.sh']]
  command: ['/usr/bin/curl']
  args: ['localhost']
  expectedOutput: ['.*OK.']
```

> --- FAIL: TestAll/Command_Test:_curl_localhost (0.00s)
	command.go:43: Please provide a valid entrypoint to run for test curl localhost

Also fails if setup appears as it does in the Dockerfile:
`setup: [["/app-cfg/entrypoint.sh"]]`

or

`setup: ["/app-cfg/entrypoint.sh"]`

**Comment by nkubala** [comment]
Hey @cognitiaclaeves,

This error is sent to the user if the `command` field isn't parsed from the config correctly: https://github.com/GoogleCloudPlatform/container-structure-test/blob/master/types/v2/command.go#L43

Can you check to make sure there aren't any trailing/leading whitespaces around your `setup` and `command` fields in your config? Everything looks fine at a glance so I think something tricky is going on there. Your setup command itself should be fine.

**Comment by cognitiaclaeves** [comment]
I'm not sure what you are asking me to do. The above copy/paste includes the command and setup args. Is this a clearer way of expressing the clause? Or are you looking for another part of the file?

```
$ cat -A structure_tests.yaml | head -9
schemaVersion: "2.0.0"$
$
commandTests:$
   - name: curl localhost$
     setup: ["/app-cfg/entrypoint.sh"]$
     command: ['/usr/bin/curl']$
     args: ['localhost']$
     expectedOutput: ['.*OK.']$
   - name: ensure nomad version$
```

> 
> === RUN   TestAll
> 2018/01/31 17:44:40 Running tests for file structure_tests.yaml
> === RUN   TestAll/Command_Test:_curl_localhost
> === RUN   TestAll/Command_Test:_ensure_nomad_version
> === RUN   TestAll/Command_Test:_ensure_nomad_path
> === RUN   TestAll/Command_Test:_ensure_flask_path
> === RUN   TestAll/File_Existence_Test:_ensure_app_directory
> === RUN   TestAll/File_Existence_Test:_ensure_hook_cfg
> === RUN   TestAll/File_Existence_Test:_ensure_nomad
> === RUN   TestAll/Metadata_Test
> --- FAIL: TestAll (1.12s)
>     --- FAIL: TestAll/Command_Test:_curl_localhost (0.00s)
>     	command.go:43: Please provide a valid entrypoint to run for test curl localhost

**Comment by nkubala** [comment]
Ah sorry, I see the problem now. [`command` is a `string`, not a `[]string`](https://github.com/GoogleCloudPlatform/container-structure-test/blob/master/README.md#command-tests). Since you're passing in a list of strings, it's not getting parsed correctly. Removing the brackets around `/usr/bin/curl` should fix it.
