### ISSUE TITLE
error while loading shared libraries: libstdc++.so.6

### ISSUE THREAD

**Issue by Evesy** [GoogleCloudPlatform/container-structure-test#59]
Hi,

I have attempted to upgrade to the latest container-structure-test version `0.2.0` however I am now receiving the below:

```
$ docker run --rm  -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/tests:/tests:ro gcr.io/gcp-runtimes/container-structure-test:v0.2.0 -test.v --image eu.gcr.io/k8-discovery-185615/platform-reverse-proxy:latest `ls tests/*.yaml`
/go_default_test: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

I do not see the same running version `0.1.3` of the container image. 

**Docker version**: 17.09.1 & 17.12.0

Cheers,
Mike

**Comment by dlorenc** [comment]
Ref https://github.com/GoogleCloudPlatform/distroless/issues/162
