### ISSUE TITLE
Error parsing YAML config

### ISSUE THREAD

**Issue by paparaka** [GoogleCloudPlatform/container-structure-test#69]
On Ubuntu 17.10 with the latest binary (22 Jan)(https://storage.googleapis.com/container-structure-test/latest/container-structure-test)

Using one of the config files in this repo (https://github.com/GoogleCloudPlatform/container-structure-test/blob/master/tests/debian_test.yaml)

The following command:
`container-structure-test -test.v -image ubuntu:16.04 debian-test.yml`

Returns the following error:
`2018/02/22 17:48:51 Error parsing config file: Please provide valid JSON or YAML config file`

**Comment by tejal29** [comment]
umm the file name is in correct? should it be debian-test.yaml?

**Comment by nkubala** [comment]
Yeah we should support `.yml` since that's also a valid YAML file extension

**Comment by paparaka** [comment]
Yes I can confirm that using "yaml" works
