### ISSUE TITLE
Different test results from tar driver for file exists test

### ISSUE THREAD

**Issue by oztigertim** [GoogleCloudPlatform/container-structure-test#72]
Using Xubuntu 16.04 64 bit on a laptop.

My yaml file has the following:
schemaVersion: '2.0.0'
fileExistenceTests:
 - name: 'Root'
   isDirectory: true
   path: '/'
   shouldExist: true
- name: 'python'
   isDirectory: true
   path: '/usr/local/bin/python'
   shouldExist: true

Running with the default docker driver the test passes.
$ sudo ./container-structure-test -test.v -image python python_file_test.yaml 
Using driver docker
=== RUN   TestAll
2018/02/28 17:18:52 Running tests for file python_file_test.yaml
=== RUN   TestAll/File_Existence_Test:_Root
=== RUN   TestAll/File_Existence_Test:_python
=== RUN   TestAll/Metadata_Test
--- PASS: TestAll (2.46s)
    --- PASS: TestAll/File_Existence_Test:_Root (2.29s)
    --- PASS: TestAll/File_Existence_Test:_python (0.17s)
    --- PASS: TestAll/Metadata_Test (0.00s)
	structure_test.go:49: Total tests run: 3

When running with the tar driver the test fails.
$ sudo ./container-structure-test -test.v -driver tar -image python python_file_test.yaml 
Using driver tar
=== RUN   TestAll
2018/02/28 17:09:22 Running tests for file python_file_test.yaml
=== RUN   TestAll/File_Existence_Test:_Root
Retrieving image python from source Cloud Registry
ERRO[0043] remove /tmp/python986107156/etc/dpkg/.wh.shlibs.default: no such file or directory 
...
INFO[0164] Finished prepping image python               
INFO[0164] Removing image filesystem directory /tmp/python885077350 from system 
--- FAIL: TestAll (164.98s)
    --- PASS: TestAll/File_Existence_Test:_Root (55.45s)
    --- FAIL: TestAll/File_Existence_Test:_python (55.48s)
    	structure.go:94: File /usr/local/bin/python should exist but does not, got error: stat /tmp/python174701923/usr/local/bin/python: no such file or directory!
    --- PASS: TestAll/Metadata_Test (54.06s)
	structure_test.go:49: Total tests run: 2
FAIL

Using the tar driver should be consistent with the docker driver.

**Comment by oztigertim** [comment]
Did a save and the /tmp folder doesn't have python in the /usr/local/bin...
/tmp# ls -la python714216499/usr/local/bin/
total 68
drwxrwsr-x  2 root root  4096 Feb 28 17:36 .
drwxrwsr-x 10 root root  4096 Feb 28 17:36 ..
-rwxr-xr-x  1 root root   101 Feb 28 17:36 2to3-3.6
-rwxr-xr-x  1 root root   239 Feb 28 17:36 easy_install
-rwxr-xr-x  1 root root   239 Feb 28 17:36 easy_install-3.6
-rwxr-xr-x  1 root root    99 Feb 28 17:36 idle3.6
-rwxr-xr-x  1 root root   211 Feb 28 17:36 pip
-rwxr-xr-x  1 root root   211 Feb 28 17:36 pip3
-rwxr-xr-x  1 root root   211 Feb 28 17:36 pip3.6
-rwxr-xr-x  1 root root    84 Feb 28 17:36 pydoc3.6
-rwxr-xr-x  1 root root 14312 Feb 28 17:36 python3.6
-rwxr-xr-x  1 root root  3109 Feb 28 17:36 python3.6m-config
-rwxr-xr-x  1 root root   441 Feb 28 17:36 pyvenv-3.6
-rwxr-xr-x  1 root root   218 Feb 28 17:36 wheel

**Comment by nkubala** [comment]
Hey @oztigertim, I'm able to repro this as well using the stock `python` image from Dockerhub. Looks like an issue with the tar extraction. Looking into it
