### ISSUE TITLE
Can -pull work with non-public images?

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/container-structure-test#83]
I have an image that is not publicly accessible.  I can pull it via `gcloud docker -- pull blah`, which is probably translated to `docker login` under the covers.  Is there a way to make this work with the structure test `-pull` flag?

If so, maybe document how do that.  Maybe I need to fiddle with permissions or environment variables.

If not, maybe document that, because the error message is really vague (`Step #0:     	docker_driver.go:241: Error creating container: no such image`) and doesn't log the actual image name it's trying.

Luckily, the workaround is fairly easy -- for my case, where I'm invoking from a cloudbuild.yaml, I add a cloudbuild step before the structure test step, that explicitly pulls the image and runs `/bin/true` in it.

Repro:

```shell
$ gcloud container builds submit --config=cloudbuild_test.yaml --substitutions=_DOCKER_NAMESPACE=gcr.io/cloud-python-runtime-qa,_TAG=2018-03-08-174800-ubuntu16 .
<snip>
Step #0: e116a9187528: Pull complete
Step #0: Digest: sha256:3e6162829f0adafeb764883a715628c91c09a5a01c5bb5a25f1662ac76bb173b
Step #0: Status: Downloaded newer image for gcr.io/gcp-runtimes/container-structure-test:v0.2.1
Step #0: Error pulling remote image gcr.io/cloud-python-runtime-qa/python:2018-03-08-174800-ubuntu16: API error (404): {"message":"pull access denied for gcr.io/cloud-python-runtime-qa/python, repository does not exist or may require 'docker login'"}
```

cloudbuild_test.yaml:
```
steps:
- name: gcr.io/gcp-runtimes/container-structure-test:v0.2.1
  args: [
   '-pull',
    '-test.v',
    '-image', 'gcr.io/cloud-python-runtime-qa/python:2018-03-08-174800-ubuntu16',
    '/workspace/tests/virtualenv/virtualenv_default.yaml',
    ]
```

**Comment by sharifelgamal** [comment]
This is definitely a credentials issue. Our container-structure-test binary supports [docker-credential-gcr](https://github.com/GoogleCloudPlatform/docker-credential-gcr) but the docker image currently doesn't (I opened #84 do support that). Currently your best workaround would be to do a docker pull into your local daemon then use the daemon prefix when referencing it.

**Comment by jghal** [comment]
I know this issue is ancient, but can this tool really not pull from private registries other than those that can be authenticated via gcr helper? I'm have my ~/.docker/config.json with the proper `.auths["<registry>"].auth` setup and can `docker pull` the image but `container-structure-test` fails indicating I need to run `docker login`.
