### ISSUE TITLE
Add support for including files in test image

### ISSUE THREAD

**Issue by nkubala** [GoogleCloudPlatform/container-structure-test#9]
We might want a way to include external files into the image under test before running the test. This used to be possible with the `--workspace` flag which would mount the workspace as a volume in the container.

**Comment by nkubala** [comment]
@meltsufin can you explain your use case for this? I'm wondering how much sense it makes to need to include files that aren't in the base image. Test scripts (for example) can be embedded in command tests.

**Comment by meltsufin** [comment]
Can you clarify how test scripts can be embedded? Some of our test scripts are rather large.

**Comment by nkubala** [comment]
You could write a command test something like this:

```
commandTests:
  - name: "long script"
    command: ["sh", "-c", <your_script_here>] 
```

Might be a bit ugly if the script is large though. In that case, I think it's probably better to instead construct intermediate images with the necessary files included in them, and then run the corresponding tests there. We actually want to avoid supporting this feature, because under the hood we have multiple implementations of the test runner (e.g. one that runs without docker), and later on this could come back to bite us. Doing a simple volume mount isn't enough here anymore.

Check out https://github.com/GoogleCloudPlatform/python-runtime/pull/160 for an example of creating intermediate images with files added, then using them in tests. I'm going to close this for now.
