### ISSUE TITLE
Run locally via Docker?

### ISSUE THREAD

**Issue by shaneog** [GoogleCloudPlatform/container-structure-test#93]
I'm trying to set this up via Docker in our CI (Buildkite) and it's not working.

I'm following the documentation and the error I'm getting is that my config file is not found.
I've tried mounting my local directory at `/workspace` and `/workspace/structure_test` to no avail.

I've tried with the released versions v1.0.0, v0.3.0 and v0.2.1.

Using [this](https://github.com/GoogleCloudPlatform/container-structure-test/blob/master/tests/debian_test.yaml) config file.

```shell
docker run --rm -i gcr.io/gcp-runtimes/container-structure-test:v0.3.0 -test.v -image ubuntu:16.04 debian-test.yaml

Using driver docker
=== RUN   TestAll
2018/03/21 15:44:52 Error parsing config file: open debian-test.yaml: no such file or directory

```

```shell
docker run --rm -i gcr.io/gcp-runtimes/container-structure-test:v1.0.0 test -v --image=ubuntu:16.04 --config debian-test.yaml

time="2018-03-21T15:50:40Z" level=fatal msg="Error parsing config file: open debian-test.yaml: no such file or directory"

```

**Comment by zemanlx** [comment]
@shaneog files are not passed to a container so it is needed to mount it as a volume `-v` like this

```bash
docker run --rm -i \
  -v ${PWD}:/src:ro \
  gcr.io/gcp-runtimes/container-structure-test:v0.3.0 \
    -test.v -image ubuntu:16.04 /src/debian-test.yaml
```

**Comment by shaneog** [comment]
Perfect, that's all I needed!

Thank you @zemanlx

**Comment by nkubala** [comment]
@zemanlx thanks for the explanation here. @shaneog it's worth noting that the real intended use case for the image we publish here is to run in [Google Cloud Container Builder](https://cloud.google.com/container-builder/docs/). Check out [this example](https://github.com/GoogleCloudPlatform/container-structure-test#running-file-tests-on-google-cloud-container-builder) from the README to see it in action. This way you don't have to worry about mounting anything into your container, just throw the image in as a build step and everything is done for you :+1:
